blank_issues_enabled: false
contact_links:
  - name: Official DFG forms and guidelines
    url: https://www.dfg.de/en/research-funding/funding-opportunities/programmes/individual/research-grants/forms-guidelines
    about: Verify current official programme requirements here.
