"""Maintainer tool: generate the TeX profile; compilation needs no generator."""
from pathlib import Path
import argparse
import json

ROOT = Path(__file__).resolve().parents[1]
PROFILE = ROOT / 'profiles/research-grants-2026-09.json'
OUTPUT = ROOT / 'dfg-research-grants-2026-09.def'

def render(profile):
    lines = ['% Generated by scripts/generate_profile.py. Edit the JSON source.',
             r'\def\DFGProfileID{' + profile['id'] + '}',
             r'\def\DFGProfileRevision{' + profile['form_revision'] + '}',
             r'\def\DFGProfileChecked{' + profile['checked'] + '}',
             r'\def\DFGMainPageMaximum{' + str(profile['main_pages']) + '}',
             r'\def\DFGSupplementPageMaximum{' + str(profile['supplement_pages']) + '}']
    for h in profile['headings'] + profile['optional_headings']:
        lines.append(r'\DFGDeclareHeading{' + h['id'] + '}{' + h['number'] + '}{' +
                     h['english'] + '}{' + h['german'] + '}{' + str(h['number'].count('.')) + '}')
    return '\n'.join(lines) + '\n'

def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check',action='store_true')
    args=parser.parse_args()
    text=render(json.loads(PROFILE.read_text(encoding='utf-8')))
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding='utf-8') != text:
            print('Generated profile is stale. Run python scripts/generate_profile.py.'); return 1
        print('Generated profile matches its source.'); return 0
    OUTPUT.write_text(text,encoding='utf-8'); return 0

if __name__=='__main__': raise SystemExit(main())
